### ISSUE TITLE
plug in not working

### ISSUE THREAD

**Issue by yasmine-ison** [CrowdStrike/CrowdDetox#2]
I put the pre-built plug-in into the plugin folder (I have many plug-ins). Nothing happens and nothing shows up under plug-in. 
Restarting ida and guest vm does nothing. 
Please advise. 
TY

**Comment by geffner** [comment]
@yasmine-ison, it sounds like CrowdDetox is functioning correctly. CrowdDetox does not add any plugin menu items and the plugin by-design doesn't perform the detox automatically.

Please refer to the usage instructions at https://github.com/CrowdStrike/CrowdDetox

**Comment by yasmine-ison** [comment]
I read the directions and it doesn't work by pushing sht+f5 once installed.

**Comment by yasmine-ison** [comment]
I read the directions and it doesn't work by pushing sht+f5 once installed.

**Comment by geffner** [comment]
Please paste the Hex-Rays decompilation that you feel CrowdDetox is not properly detoxing.

**Comment by yasmine-ison** [comment]
@geffner Unfortunately even though I was using it to help reverse engineer malware, because of the sensitivity of my work, I can't post that information. I found this tool because another Reverse Engineer mentioned using it to help remove junk code from a similar piece of malware.  A little vague but I hope that helps.
I took the file hexrays_CrowdDetox.plw and dropped into the plug in folder, once my malware was loaded, I pushed sht+F5. Nothing happened.

**Comment by geffner** [comment]
What version of IDA are you using, and can you confirm that you have the Hex-Rays decompiler installed?

**Comment by yasmine-ison** [comment]
@geffner  I have IDA 6.8 and yes I have Hex-Rays installed.

**Comment by geffner** [comment]
Recent versions of IDA Pro (including 6.8) bind `Shift+F5` to open the Signatures view. As such, you'd need to edit [the hotkey](https://github.com/CrowdStrike/CrowdDetox/blob/master/CrowdDetox.cpp#L1240) for CrowdDetox and [rebuild it](https://github.com/CrowdStrike/CrowdDetox/blob/master/README#L14) to use it for recent versions of IDA Pro.

**Comment by yasmine-ison** [comment]
I will try this and let you know. Ty
