### ISSUE TITLE
Rebuild for recent versions of IDA

### ISSUE THREAD

**Issue by Mewgood** [CrowdStrike/CrowdDetox#3]
Can you do a rebuild for more recent versions of IDA, with a new shortcut?

I am trying to do this myself, and I've run into this issue when compiling the module:
`            if (pItem->op == cot_var)
            {
                if (!afVariableIsLegit[((cexpr_t*)pItem)->v.idx])
                {
                    if (T_NORMAL != print_type_to_one_line(
                        szType,
                        _countof(szType),
                        idati,
                        ((cexpr_t*)pItem)->type.u_str()))
                    {
                        return 0;
                    }
                    if (0 != strcmp(szType, "CPPEH_RECORD"))
                    {
                        return 0;
                    }
                }
            }`

T_NORMAL is not defined and u_str() is not a defined member of tinfo_t. T_NORMAL was #defined as 0 in SDK 6.4, but I do not know what the equivalent of u_str() would be in my version of IDA (6.8).

**Comment by shawndwells** [comment]
Hi @Mewgood - apologies for the years delay! As you may have guessed, this project has not been maintained for some time. We've no archived it.

**Comment by shawndwells** [comment]
We've *now archived it.
